### ISSUE TITLE
Bitte Dorsten eintragen

### ISSUE THREAD

**Issue by Ziltoidium** [ffruhr/ffapi#3]
Ich hoffe, ich bin hier diesmal richtig (Ort und tool).
Ansonsten steinigt mich :-)
Ich glaube für Dorsten gibt es noch keine Community, es sind zwar drei Knoten im Osten verzeichnet, aber es ist keine Community im Dropdown auf der Karte

http://oliverritter.com/ffdorsten/FreifunkDorsten-api.json

**Comment by DaCHRIS** [comment]
Du musst Deine Veränderungen hier in die Datei eintragen:

https://github.com/ffruhr/ffapi/blob/master/dorsten.json

Sobald Du die Veränderungen in der Datei gemacht hast und diese gemerged sind ist es automatisch live...

**Comment by christian-weiss** [comment]
Dieses Repository hier wird schon lange nicht mehr gepflegt wird, weil die github organization ffruhr nach der Auflösung von Freifunk Ruhrgebiet inaktiv geworden ist. Solltest Du zukünftig Community API Dateien, die ehemals zum Freifunk Ruhrgebiet zählten, bearbeiten wollen, kannst Du nun Issues und Pull Requests hier erstellen: https://github.com/Freifunk-Hamm/ffapi

Im Freifunk Community Directory zeigen die ehemaligen Freifunk Ruhrgebiet Communities seit Kurzem genau auf o.g. Repo - es ist also bereits aktiv. Wir freuen uns, das es jetzt wieder eine Möglichkeit gibt, einfach und schnell Änderungen an den Dateien vornehmen zu können (für alle die die Datei nicht selbst hosten möchten).

@Ziltoidium bitte dieses Ticket hier schließen.
